### ISSUE TITLE
Mismatching documentation

### ISSUE THREAD

**Issue by hawkup** [dulnan/nuxt-multi-cache#1]
I tried to use `nuxt-multi-cache` with my project and found the different usage and the documentation. 

1. **the object name of module on nuxt.config.js**
Documentation told to use `multiCache` for object name
But I have to use `routeCache` to make it works.

2. **the server auth config**
Documentation told to use `serverAuth` for server auth config 
But I have to use
```javascript
server: {
  auth: {
    username: ''
    password: ''
  }
}
```

----
nuxtjs version: `2.15.7`
nuxt-mult-cache version: `1.0.5`

This is the config I use
```javascript
routeCache: {
  enabled: true,
  debug: true,
  outputDir: '~/cache',
  server: {
    auth: {
      username: 'admin',
      password: 'hunter2'
    }
  },
  pageCache: {
    enabled: true
  },
  dataCache: {
    enabled: true
  }
}
```

**Comment by dulnan** [comment]
Thank you for reporting this issue! There is a mismatch between what's published on npm and what's in the repo. I will publish a new relase that gets npm, repo and docs in sync.
