### ISSUE TITLE
Route caching is not working correctly in Nuxt 3

### ISSUE THREAD

**Issue by sterzuccio** [dulnan/nuxt-multi-cache#11]
I am having issues using this module with version 3 of nuxt. I have added the enable and store parameters in the `nuxt.config.ts` file to use cacheRoute. In each page, inside the `<script setup>` tag, I have added the function 
```
useRouteCache((route) => {
route
.setMaxAge(3600)
.setCacheable()
.addTags([“tag”])
})
```
When I navigate on my site, the cache files are not stored, but if I manually reload the page, the files are created. How is this possible?
The routing is dynamic and the structure is as follows:

![Schermata 2023-03-24 alle 10 28 01](https://user-images.githubusercontent.com/14995053/227480342-47a4fd89-3dad-4cca-9e76-e486dbfdc1b1.png)

I also tried to include the useRouteCache function inside the `<script>` tag within `created()`, but importing useRouteCache gives me the following issue:
 `ERROR  Internal server error: Missing "./dist/runtime/composables" specifier in "nuxt-multi-cache" package`

**Comment by dulnan** [comment]
When you navigate the page in the browser the browser does the rendering, so no SSR is happening. The route cache is SSR-only: It caches the entire markup of the rendered page and serves this on every subsequent request. That‘s why when you reload the page it‘s working.

One way to make sure the route cache is working is to put a console.log in a component where you know it‘s being rendered on the server. When you refresh a page multiple times you should be seeing the logged message only once in the console.
