### ISSUE TITLE
Cannot cache same route with different tags

### ISSUE THREAD

**Issue by niddu85** [dulnan/nuxt-multi-cache#13]
I'm trying to cache a route (the homepage of my website) on redis depending on the language.
The same page responds with different HTMLs depending on the selected language (eg www.site.com is for english, fr.site.com is for french, de.site.com is for german...), but if i cache the page using 

```
const currentLanguage = getCurrentLanguage();

  useRouteCache((helper) => {
    helper
      .setMaxAge(300)
      .setCacheable()
      .addTags([
    `page:homepage`,
    `lang:${currentLanguage}`,
  ]);
  });
```

only one entry is saved on Redis.

How can i accomplish this?

thanks in advance

**Comment by dulnan** [comment]
Currently this is not directly possible, as the cache key is derived from the path only. But I have already made preparations to support such a use case, where a custom prefix can be provided (per request). As I'm currently working on proper support for Nuxt 3.4.x, I will consider adding this feature in the next release.
