### ISSUE TITLE
Has no effect on nuxt3 route caching

### ISSUE THREAD

**Issue by wf-soft** [dulnan/nuxt-multi-cache#15]
This library does not seem to cache nuxt3 pages.

**Comment by dulnan** [comment]
Not sure what the exact cause for your issue was, but I just released a new version `3.0.0` that might solve your problem. Please give it a try, if the route cache still doesn't work for you, I'll gladly assist debugging.

**Comment by wf-soft** [comment]
@dulnan I want to use a function similar to VUE's keepalite, because Nuxt3's keepalite contains / excludes Bug. I don't know if this library can implement page caching or if there are any new examples.
