### ISSUE TITLE
Redis TTL

### ISSUE THREAD

**Issue by SqrTT** [dulnan/nuxt-multi-cache#20]
Currently ttl is not passed during `setItem` call as result TTL is not set for Redis.

This causes that Redis can't remove records in different circumstances, for instance when no free memory left and to add new record Redis have to remove some old records. Having TTL redis could remove records which have lower TTL which expire anyway soon. 

Basically, having TTL in Redis record may increase efficiency of Redis usage and memory usage by better cleanup.

Add should not be complicated since `setItem` support third parameter

https://github.com/dulnan/nuxt-multi-cache/blob/main/src/runtime/serverHandler/responseSend.ts#L96-L98

**Comment by dulnan** [comment]
Makes sense, thanks for your suggestion! I will add the third argument to pass the TTL in the setItem method. The TTL value will be based on the max age that is being set from the useRouteCache helper. I think this would be the expected behavior.

**Comment by dulnan** [comment]
This is implemented in the 3.1.0 release.
