### ISSUE TITLE
useRuntimeConfig crashes app in case cdn enabled

### ISSUE THREAD

**Issue by SqrTT** [dulnan/nuxt-multi-cache#22]
usage non-imported `useRuntimeConfig` causes app to crash

![image](https://github.com/dulnan/nuxt-multi-cache/assets/1271300/f08c5d2f-eba9-460c-9ed0-a07767274559)

Probably it's caused because it's not imported via 
```js
import { useRuntimeConfig } from '#imports'
```
like in other places

![image](https://github.com/dulnan/nuxt-multi-cache/assets/1271300/dd2fb772-157f-4889-a201-6759da59950d)

**Comment by SqrTT** [comment]
is there any update?

there is reproduce
https://codesandbox.io/p/sandbox/dazzling-sound-ng5grt?file=%2Fnuxt.config.ts%3A5%2C1-10%2C7

**Comment by dulnan** [comment]
This is now fixed in the 3.1.0 release.
