### ISSUE TITLE
Data cache outside component

### ISSUE THREAD

**Issue by or2e** [dulnan/nuxt-multi-cache#23]
Hello )

I am trying to make data caching work when called in a server plugin or server middleware
As far as I understand, there must be a vue component where useDataCache is called

My scenario:
In `plugins/init.server.ts` I do a global data load. Unfortunately, doing it in `app.vue` is not working for me, coz I need this data in several `middleware`, and they are processed after `app.vue` ref: https://miro.medium.com/v2/resize:fit:828/format:webp/1*v-pnTrIP-Kq29k52BIGp8g.png

**Comment by dulnan** [comment]
You can call `useDataCache` also in a plugin. Bascially anywhere you can also call any other composable. It also works in a server context (e.g. server handler).
