### ISSUE TITLE
Verbose runtime option

### ISSUE THREAD

**Issue by or2e** [dulnan/nuxt-multi-cache#24]
Hi ;)
It would be useful to add an option for log management

Scenario: in dev-mode it is necessary to turn off cache components, then we get [log messages](https://github.com/dulnan/nuxt-multi-cache/blob/main/src/runtime/components/RenderCacheable/index.ts#L159)

<details>
  <summary>Log</summary>

  ![image](https://github.com/dulnan/nuxt-multi-cache/assets/33551334/1e11ea8e-a6f4-4f41-95f3-3dee3b0cab48)
</details>

Temporary solution: use prop `:noCache`

<details>
  <summary>Example</summary>
  
```
export const useCacheEnabled = () => {
    const { isServer } = useProcess();
    const noCache = computed(
        () => isServer && useRuntimeConfig().multiCache.component === false
    );

    return {
        noCache,
    };
};

...
const { noCache } = useCacheEnabled();
...
RenderCacheable(:noCache='noCache')
```
</details>

Unfortunately, I couldn't make a wrapper for the RenderCacheable component, because of [this part](https://github.com/dulnan/nuxt-multi-cache/blob/main/src/runtime/components/RenderCacheable/helpers/index.ts#L43)

**Comment by dulnan** [comment]
Thank you for raising this issue, I have removed all non-error log messages, not only on the component cache but also in other places. They are now only logged when setting the new `debug` option. It is available in the 3.1.0 release.
