### ISSUE TITLE
BugReport: unable to import MultiCacheConfig in node_modules/types/Cache/Data/index.d.ts

### ISSUE THREAD

**Issue by bernaoliveira** [dulnan/nuxt-multi-cache#3]
![bad import](https://user-images.githubusercontent.com/45824272/154860995-538dd3b7-830c-4138-9a5e-cd53a6f39a9c.png)

Here we can see an error, that appears in nuxt-ts runtime.
It can be me catched also in node_modules/types/Cache/Component/index.d.ts and node_modules/types/Cache/Groups/index.d.ts

Adding import { MultiCacheConfig } from '../../config' fixes the issue.

**Comment by dulnan** [comment]
Thank you for the bug report, I have fixed the wrong import paths and published a new release.
