### ISSUE TITLE
Exclude cookies from route caching headers

### ISSUE THREAD

**Issue by unluckynelson** [dulnan/nuxt-multi-cache#30]
Caching the cookies with a request is very problematic, as tracking cookies are then cached and breaks tracking. 
Any user selection around privacy cookie or settings is overwritten.

Please can we exclude caching Cookie headers

**Comment by brandon-gs** [comment]
I agree, also in my case I can't use this package because it saved cookies with authentication token.

**Comment by dulnan** [comment]
I've now implemented a way to alter which headers should be stored in cache, using the new `route.alterCachedHeaders` option. That way it's possible to completely remove the `Set-Cookie` header (or any other header) or do more granular adjustments (e.g. only remove certain cookies).
