### ISSUE TITLE
First Response is empty in netlify when caching route

### ISSUE THREAD

**Issue by Rigo-m** [dulnan/nuxt-multi-cache#32]
Server handler in netlify when cache is a miss and I've cached the route using useRouteCache the response is completely empty (no html no nothing), refreshing the page works as intended

**Comment by dulnan** [comment]
This should now (hopfeully) be fixed in 3.3.0 due to refactoring how the route cache works. I can't test it myself for Netlify, but a similar issue popped up with Cloudflare Workers and there it now works.
