### ISSUE TITLE
Bug: $cache.route.setCacheable() instead $cache.page.setCacheable()

### ISSUE THREAD

**Issue by IfnotFr** [dulnan/nuxt-multi-cache#4]
Hello,

First, thanks for this awesome plugin, I started making my own cache plugin because none of the ecosystem was good enough, but finally I found yours and he is perfect :)

The bug :
I tried to use the page cache using `$cache.page.setCacheable()` as described on the documentation but it looks that you changed to API to `$cache.route.setCacheable()` ?

**Comment by admg** [comment]
Same problem here. When I'm using code from documentation I get: `Error in fetch(): Cannot read property 'setCacheable' of undefined`

**Comment by dulnan** [comment]
Thank you for the bug report. Indeed, I somehow forgot to update the documentation to reflect the changes I made, which actually makes the main feature of this module unusable - what a fail.
The usage is `$cache.route.setCacheable()`, as you correctly pointed out.

I will update the documentation accordingly and deploy the updated docs.

**Comment by dulnan** [comment]
The updated docs have been published. Thanks again for bringing this up!
