### ISSUE TITLE
How to set expiration time for data cache?

### ISSUE THREAD

**Issue by 4tech-zun** [dulnan/nuxt-multi-cache#6]
Hi,
I want to ask how to set expiration time for data cache, I can't find it in the documentation.
Currently the only way to clear manually is to call the API.

Thank you!

**Comment by dulnan** [comment]
You can use the `lruOptions` on the `dataCache` configuration property for this:
https://github.com/dulnan/nuxt-multi-cache/blob/main/src/config.ts#L125

This module uses lru-cache as the in-memory caching backend. It's still using version 6, which has different options than the latest 7.x releases. Here's the options for the 6.x releases: https://github.com/isaacs/node-lru-cache/tree/v6.0.0

To have a max age for data cache entries, this example should work:

```typescript
module.exports = {
  modules: ['nuxt-multi-cache'],

  multiCache: {
    enabled: true,
    dataCache: {
      enabled: true,
      lruOptions: {
        maxAge: 2 * 60 * 60 * 1000 // 2 hours
      }
    }
  }
}
```

**Comment by 4tech-zun** [comment]
Hi @dulnan  
Thank you for your fast reply, It works perfectly.
