### ISSUE TITLE
Return type of useCachedAsyncData is any

### ISSUE THREAD

**Issue by jonathanwilke** [dulnan/nuxt-multi-cache#68]
Hey,

I really like the latest update with useCachedAsyncData as it makes the code so much cleaner. One issue I do have with it though is the return type of any. 

<img width="1474" alt="Bildschirmfoto 2024-08-13 um 14 22 50" src="https://github.com/user-attachments/assets/cde8c41a-5e09-4b6b-b765-51f6e4480d4c">

Could we make this typed as everything else?

**Comment by dulnan** [comment]
This is indeed a bug in the module, while the arguments are typed, the method's return type is not. Will fix this.
