### ISSUE TITLE
componets and data caching is not enabled when the route caching is not enabled

### ISSUE THREAD

**Issue by majtanmarek** [dulnan/nuxt-multi-cache#69]
It seems like with this configuration (route.enabled=false) is data and component not enabled as well, because nitro plugin is not loaded

  multiCache: {
    route: {
      enabled: false,
    },
    data: {
      enabled: true,
    },
    component: {
      enabled: true
    },
  },

After a long research, I tried to enable route because of this peace of code (maybe it is not exactly the bug, but it was my clue)

nuxt-multi-cache/dist/module.mjs:121

   if (options.route?.enabled || options.cdn?.enabled || nuxt.options._prepare) {
      addServerPlugin(resolve("./runtime/server/plugins/multiCache"));
    }

**Comment by dulnan** [comment]
Uff, good catch. And it didn't get caught by tests because they always enable all caches :man_facepalming: I fixed the bug and also adapted all tests to make sure this can't happen in the future.
