### ISSUE TITLE
serverMaxAge: 0 not working when using useCachedAsyncData

### ISSUE THREAD

**Issue by jonathanwilke** [dulnan/nuxt-multi-cache#78]
Hey there,

first of all, we love your tool and are really thankful for all your work here!

Today we found a little issue when using useCachedAsyncData(). In this specific case we only wanted to utilize it for client-side caching so we set serverMaxAge to 0. The expected behavior was that no cache is written on server-side at all, but instead it would just cache the data without a ttl.

**Comment by dulnan** [comment]
Ha, good find. Makes me wonder if this is handled consistently across the module, will have to check.

So I guess anything `<= 0` would imply *don't cache*. And `undefined` or `null` would mean *cache without a max age*. And any value `>= 1` would cache and set that as the max age.

**Comment by dulnan** [comment]
Released in 3.4.0
