### ISSUE TITLE
Page cache enabled but not really caching the page. 

### ISSUE THREAD

**Issue by ahmadmobaraki** [dulnan/nuxt-multi-cache#8]
Thank you for this awesome module!
I'm trying to cache the entire page, inside the page (in fetch hook), I call  the API to get product details.
Then when I enable the page cache, I see it's actually caching it by the route as the key. I see it is cached by checking localhost:3000/__nuxt_multi_cache/stats/page. Even can see the logs in nuxtjs server that says the page cached...

But seems it's still calling the API every time when I refresh the page, I'm seeing the request logs in backend. Also lighthouse scores not changed in local, so no performance increase. 

So as I understood, it must directly load the html file from cache with populated data, so no call to API, am I correct? If yes,  how can I debug this issue? I see no errors in browser console or nuxtjs server. 

I call the `this.$cache.route.setCacheable()` inside fetch() after getting product from API. 
This is my config:  

```
  modules: [
    '@nuxtjs/i18n',
    '@nuxtjs/axios',
    '@nuxtjs/auth-next',
    '@nuxtjs/pwa',
    'nuxt-multi-cache',
  ],
  
multiCache: {
    enabled: true,
    outputDir: './cache',
    debug: true,
    server: {
      auth(req) {
        return true
      },
    },
    pageCache: {
      enabled: true
    },
    dataCache: {
      enabled: true,
    },

    componentCache: {
      enabled: true,
      lruOptions: {
        max: 1000,
        maxAge: 24 * 60 * 60 * 1000, // 24 hours
      },
    },
  },
```

**Comment by dulnan** [comment]
You're correct, when a cached page is served then it immediately returns the cached markup pretty early on, no Vue rendering is happening.

Is it possible that the API request happen again on the client side, after the cached page was returned?

Lighthouse score might not be affected if the response time is anyway very low: If (without cache) a response takes ~100ms and with cache ~50ms, then that likely doesn't make a huge difference.

**Comment by ahmadmobaraki** [comment]
Thanks for the fast reply, No it all happens in fetch hook. The page structure is like this:
pages/_category/_slug.vue

And then inside fetch I have some conditions to check if the route is category or a product... and only call `this.$cache.route.setCacheable()` and call  to API to get product only  when it's product, not category... but this shouldn't cause the issue, right? weird

**Comment by dulnan** [comment]
The way you describe it sounds correct. A page with dynamic params can be cached dynamically, as you described.

In order to rule out any other problems, can you try putting a console.log in your fetch() hook and then see if the message is logged more than once when visiting the same cached route?

**Comment by ahmadmobaraki** [comment]
Yes I'm seeing the log every time!

**Comment by dulnan** [comment]
Okay, so it seems to be indeed a bug. Which exact versions are you using (Nuxt and this module)? I will then try to reproduce it.

**Comment by ahmadmobaraki** [comment]
Thanks!

"nuxt": "^2.15.7"
"nuxt-multi-cache": "^1.2.0"
nodejs v14.21.1

Not sure it it's related, we are using "@nuxtjs/i18n": "^7.3.0",  so we have multi language website, with the following config:

```
i18n: {
    baseUrl: process.env.BASE_URL,
    defaultLocale: 'en',
    strategy: 'prefix_except_default',
    detectBrowserLanguage: false,
    parsePages: false,
    vueI18n: {
      fallbackLocale: 'en',
    }......
```

**Comment by ahmadmobaraki** [comment]
@dulnan  most probably the issue is my nginx config, I will notify you when I fixed it.

**Comment by ahmadmobaraki** [comment]
Ok, the issue is not nginx, It's the dynamic route. 

When I create a vue file inside _category directory, like this:  pages/_category/test.vue ,  the cache works and calls the API only once,  but when I try the exact same code inside  pages/_category/_slug.vue. It's not caching it!  So it has issues with last part of the URL being dynamic. 

This is the code inside both components:
```
<template>
  <div>
    <div v-if="showProduct">
      {{ product.name }}
    </div>
  </div>
</template>

<script>

export default {
  name: 'CategoryProductPage',

  data() {
    return {
      product: null,
    }
  },

  async fetch() {
    await this.fetchProduct()
    this.$cache.route.setCacheable()
  },

  computed: {
    showProduct() {
      return this.product && this.product?.id
    },
  },

  methods: {
    async fetchProduct() {
      await this.$store.dispatch('products/get', 1)
      const product = this.$store.getters['products/currentProduct']
      this.product = product
    },
  },
}
</script>
```

I tried 'static' mode and memory mode, both resulted in the same behavior. Also I'm did not use dev mode, I run `npm run build` and the `start` every time, and cleared the cached HTML files.

**Comment by dulnan** [comment]
Thank you very much for investigating and providing these details! I will try to reproduce it locally and hopefully figure out the issue.

**Comment by dulnan** [comment]
I created a repo with the provided setup, using the listed modules in the correct version.
https://github.com/dulnan/nuxt2-multi-cache-debug

Cloning the repo, running `npm install`, `npm run build` and then starting the demo API using `npm run api` in one terminal and starting Nuxt with  `npm run start` in another terminal, I open this URL: http://localhost:3000/fr/category-foo/something and refresh the page several times. I only see a single logged message from the API app, indicating that the request is only made once and that the page is cached and afterwards served from cache.

I assume the error must be somewhere in your app, either by a specific combination of module settings or by a bug somewhere in the pages/store logic.

Can you have a look at the demo app, especially the nuxt.config.js? The closer it is to your setup, the easier. Ideally you can also reproduce it in there using your configuration/code.

**Comment by ahmadmobaraki** [comment]
Hi @dulnan , thank you so much for the support so far. 
I finally narrowed down the issue and reproduced it in your debug repo!
This is the PR: 
[](https://github.com/dulnan/nuxt2-multi-cache-debug/pull/1)

To give you some context, the issue was my top navbar component inside the layout. For some entities (like products), we have only specific languages available, we detect this from product details coming from API, and the set the available languages into the store. Now to show what other languages the current product is available in, I use the `store.getter`  inside the navbar to get available languages and filter out all languages based on it ($i18n.locales). Just see my PR :))

**Comment by ahmadmobaraki** [comment]
If you dont use store.getter inside the navbar and just use hardcoded available languages like the following, it works fine and calls the API once only:

```
{
        en: "enabled",
        fr: "enabled",
        es: "disabled",
 }
```

**Comment by ahmadmobaraki** [comment]
@dulnan I realized when I initialize the `currentEntityLangStatus`  with an empty object instead of null, it works correctly!

So instead of this:
```
export const state = () => ({
  currentEntityLangStatus: null,
});
```  
Use this:
```
export const state = () => ({
  currentEntityLangStatus: {},
});
```

And now it caches it correctly!!

**Comment by dulnan** [comment]
Wow, that‘s weird! I‘m really curious why that happens. Does the page not render correctly if you use null? Throwing errors?

**Comment by ahmadmobaraki** [comment]
> Wow, that‘s weird! I‘m really curious why that happens. Does the page not render correctly if you use null? Throwing errors?

It renders correctly! calls the API and shows product details.
