### ISSUE TITLE
Caching Pages Question

### ISSUE THREAD

**Issue by perusoa** [dulnan/nuxt-multi-cache#9]
Hi There! I just started using this module and was curious if theres a setting I am possibly missing. I have the following configuration in my nuxt config:
```
multiCache: {
    enabled: true,
    outputDir: '~/cache',
    server: {
      auth: {
        username: 'admin',
        password: 'hunter2'
      },
    },
    pageCache: {
      enabled: true,
      lruOptions: {
        max: 100,
        maxSize: 5000,
        ttl: 1000 * 60 * 1, // 1 Minutes
        allowStale: false,
      },
    },
  },
```
Since I have the TTL set for 1 minute I was expecting that after 1 minute, the `/__nuxt_multi_cache/stats/page` API endpoint wouldn't returned a cached page that was expired. Is a cached page supposed to be removed from the API response after it expires? Currently this is my response for simply my homepage:
```
{
    "rows": [
        {
            "tags": [],
            "timestamp": 1675953158830,
            "key": "/"
        }
    ],
    "total": 1
}
```
But the page expired already (at least I think it should have lol).

Any insight would be awesome! thanks and so far this module looks great/exactly what I was looking for!!

**Comment by dulnan** [comment]
I assume you're using the Nuxt 2 version, right? There it's using `lru-cache` in version 6, which has a different configuration options than the current version (7.x). Here's the docs for 6.x: https://github.com/isaacs/node-lru-cache/tree/a71e08008f2d25442426d0d26e8133dccc2ca9a5

One of the things they changed was renaming `maxAge` to `ttl`. So in your case it should work this way:

```
lruOptions: {
  max: 100,
  maxAge: 1000 * 60 * 1, // 1 Minutes
  stale: false,
}
```

**Comment by perusoa** [comment]
Ah dude that did the trick! you da man! Thank you so muc, seriously this module already is exactly what i was looking for!

**Comment by dulnan** [comment]
Thanks, I'm glad you like it!
